# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.miscelleneous_api import MiscelleneousApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMiscelleneousApi(unittest.TestCase):
    """MiscelleneousApi unit test stubs"""

    def setUp(self):
        self.api = MiscelleneousApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_i_invoice_id_get(self):
        """Test case for i_invoice_id_get

        Invoice checkout  # noqa: E501
        """
        pass

    def test_lang_codes(self):
        """Test case for lang_codes

        Language codes  # noqa: E501
        """
        pass

    def test_permissions_metadata(self):
        """Test case for permissions_metadata

        Permissions metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
