# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_create_lightning_invoice_request_expiry import AllOfCreateLightningInvoiceRequestExpiry  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfCreateLightningInvoiceRequestExpiry(unittest.TestCase):
    """AllOfCreateLightningInvoiceRequestExpiry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfCreateLightningInvoiceRequestExpiry(self):
        """Test AllOfCreateLightningInvoiceRequestExpiry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_create_lightning_invoice_request_expiry.AllOfCreateLightningInvoiceRequestExpiry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
