# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.store_payment_methods_api import StorePaymentMethodsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStorePaymentMethodsApi(unittest.TestCase):
    """StorePaymentMethodsApi unit test stubs"""

    def setUp(self):
        self.api = StorePaymentMethodsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_store_payment_methods_get_store_payment_methods(self):
        """Test case for store_payment_methods_get_store_payment_methods

        Get store payment methods  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
