# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pull_payments__public_api import PullPaymentsPublicApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPullPaymentsPublicApi(unittest.TestCase):
    """PullPaymentsPublicApi unit test stubs"""

    def setUp(self):
        self.api = PullPaymentsPublicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pull_payments_create_payout(self):
        """Test case for pull_payments_create_payout

        Create Payout  # noqa: E501
        """
        pass

    def test_pull_payments_get_payout(self):
        """Test case for pull_payments_get_payout

        Get Payout  # noqa: E501
        """
        pass

    def test_pull_payments_get_payouts(self):
        """Test case for pull_payments_get_payouts

        Get Payouts  # noqa: E501
        """
        pass

    def test_pull_payments_get_pull_payment(self):
        """Test case for pull_payments_get_pull_payment

        Get Pull Payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
