# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.on_chain_payment_method_data_preview import OnChainPaymentMethodDataPreview  # noqa: E501
from swagger_client.rest import ApiException


class TestOnChainPaymentMethodDataPreview(unittest.TestCase):
    """OnChainPaymentMethodDataPreview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnChainPaymentMethodDataPreview(self):
        """Test OnChainPaymentMethodDataPreview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.on_chain_payment_method_data_preview.OnChainPaymentMethodDataPreview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
