# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_on_chain_automated_transfer_settings import UpdateOnChainAutomatedTransferSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateOnChainAutomatedTransferSettings(unittest.TestCase):
    """UpdateOnChainAutomatedTransferSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateOnChainAutomatedTransferSettings(self):
        """Test UpdateOnChainAutomatedTransferSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_on_chain_automated_transfer_settings.UpdateOnChainAutomatedTransferSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
