# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.payout_processors_api import PayoutProcessorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPayoutProcessorsApi(unittest.TestCase):
    """PayoutProcessorsApi unit test stubs"""

    def setUp(self):
        self.api = PayoutProcessorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payout_processors_get_payout_processors(self):
        """Test case for payout_processors_get_payout_processors

        Get payout processors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
