# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygreenfield
from pygreenfield.models.on_chain_wallet_transaction_data import OnChainWalletTransactionData  # noqa: E501
from pygreenfield.rest import ApiException


class TestOnChainWalletTransactionData(unittest.TestCase):
    """OnChainWalletTransactionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnChainWalletTransactionData(self):
        """Test OnChainWalletTransactionData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.on_chain_wallet_transaction_data.OnChainWalletTransactionData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
