# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.on_chain_wallet_address_data import OnChainWalletAddressData  # noqa: E501
from swagger_client.rest import ApiException


class TestOnChainWalletAddressData(unittest.TestCase):
    """OnChainWalletAddressData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnChainWalletAddressData(self):
        """Test OnChainWalletAddressData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.on_chain_wallet_address_data.OnChainWalletAddressData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
