# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.lnurl_pay_payment_method_data import LNURLPayPaymentMethodData  # noqa: E501
from swagger_client.rest import ApiException


class TestLNURLPayPaymentMethodData(unittest.TestCase):
    """LNURLPayPaymentMethodData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLNURLPayPaymentMethodData(self):
        """Test LNURLPayPaymentMethodData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.lnurl_pay_payment_method_data.LNURLPayPaymentMethodData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
