# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.invoice_additional_status import InvoiceAdditionalStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestInvoiceAdditionalStatus(unittest.TestCase):
    """InvoiceAdditionalStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoiceAdditionalStatus(self):
        """Test InvoiceAdditionalStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.invoice_additional_status.InvoiceAdditionalStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
