# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygreenfield
from pygreenfield.models.point_of_sale_app_data import PointOfSaleAppData  # noqa: E501
from pygreenfield.rest import ApiException


class TestPointOfSaleAppData(unittest.TestCase):
    """PointOfSaleAppData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointOfSaleAppData(self):
        """Test PointOfSaleAppData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.point_of_sale_app_data.PointOfSaleAppData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
