# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pygreenfield
from pygreenfield.models.webhook_data import WebhookData  # noqa: E501
from pygreenfield.rest import ApiException


class TestWebhookData(unittest.TestCase):
    """WebhookData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookData(self):
        """Test WebhookData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.webhook_data.WebhookData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
