# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.checkout_options import CheckoutOptions  # noqa: E501
from swagger_client.rest import ApiException


class TestCheckoutOptions(unittest.TestCase):
    """CheckoutOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckoutOptions(self):
        """Test CheckoutOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.checkout_options.CheckoutOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
