# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_key_data import ApiKeyData  # noqa: E501
from swagger_client.rest import ApiException


class TestApiKeyData(unittest.TestCase):
    """ApiKeyData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiKeyData(self):
        """Test ApiKeyData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_key_data.ApiKeyData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
