# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectToNodeRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'node_uri': 'str'
    }

    attribute_map = {
        'node_uri': 'nodeURI'
    }

    def __init__(self, node_uri=None):  # noqa: E501
        """ConnectToNodeRequest - a model defined in Swagger"""  # noqa: E501
        self._node_uri = None
        self.discriminator = None
        if node_uri is not None:
            self.node_uri = node_uri

    @property
    def node_uri(self):
        """Gets the node_uri of this ConnectToNodeRequest.  # noqa: E501

        Node URI in the form `pubkey@endpoint[:port]`  # noqa: E501

        :return: The node_uri of this ConnectToNodeRequest.  # noqa: E501
        :rtype: str
        """
        return self._node_uri

    @node_uri.setter
    def node_uri(self, node_uri):
        """Sets the node_uri of this ConnectToNodeRequest.

        Node URI in the form `pubkey@endpoint[:port]`  # noqa: E501

        :param node_uri: The node_uri of this ConnectToNodeRequest.  # noqa: E501
        :type: str
        """

        self._node_uri = node_uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectToNodeRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectToNodeRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
