# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OnChainWalletFeeRateData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'feerate': 'float'
    }

    attribute_map = {
        'feerate': 'feerate'
    }

    def __init__(self, feerate=None):  # noqa: E501
        """OnChainWalletFeeRateData - a model defined in Swagger"""  # noqa: E501
        self._feerate = None
        self.discriminator = None
        if feerate is not None:
            self.feerate = feerate

    @property
    def feerate(self):
        """Gets the feerate of this OnChainWalletFeeRateData.  # noqa: E501

        The fee rate (sats per byte) based on the wallet's configured recommended block confirmation target  # noqa: E501

        :return: The feerate of this OnChainWalletFeeRateData.  # noqa: E501
        :rtype: float
        """
        return self._feerate

    @feerate.setter
    def feerate(self, feerate):
        """Sets the feerate of this OnChainWalletFeeRateData.

        The fee rate (sats per byte) based on the wallet's configured recommended block confirmation target  # noqa: E501

        :param feerate: The feerate of this OnChainWalletFeeRateData.  # noqa: E501
        :type: float
        """

        self._feerate = feerate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OnChainWalletFeeRateData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OnChainWalletFeeRateData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
