# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateOnChainAutomatedTransferSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'interval_seconds': 'AllOfUpdateOnChainAutomatedTransferSettingsIntervalSeconds'
    }

    attribute_map = {
        'interval_seconds': 'intervalSeconds'
    }

    def __init__(self, interval_seconds=None):  # noqa: E501
        """UpdateOnChainAutomatedTransferSettings - a model defined in Swagger"""  # noqa: E501
        self._interval_seconds = None
        self.discriminator = None
        if interval_seconds is not None:
            self.interval_seconds = interval_seconds

    @property
    def interval_seconds(self):
        """Gets the interval_seconds of this UpdateOnChainAutomatedTransferSettings.  # noqa: E501

        How often should the processor run  # noqa: E501

        :return: The interval_seconds of this UpdateOnChainAutomatedTransferSettings.  # noqa: E501
        :rtype: AllOfUpdateOnChainAutomatedTransferSettingsIntervalSeconds
        """
        return self._interval_seconds

    @interval_seconds.setter
    def interval_seconds(self, interval_seconds):
        """Sets the interval_seconds of this UpdateOnChainAutomatedTransferSettings.

        How often should the processor run  # noqa: E501

        :param interval_seconds: The interval_seconds of this UpdateOnChainAutomatedTransferSettings.  # noqa: E501
        :type: AllOfUpdateOnChainAutomatedTransferSettingsIntervalSeconds
        """

        self._interval_seconds = interval_seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateOnChainAutomatedTransferSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateOnChainAutomatedTransferSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
