# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WithdrawalRequestData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payment_method': 'str',
        'qty': 'float'
    }

    attribute_map = {
        'payment_method': 'paymentMethod',
        'qty': 'qty'
    }

    def __init__(self, payment_method=None, qty=None):  # noqa: E501
        """WithdrawalRequestData - a model defined in Swagger"""  # noqa: E501
        self._payment_method = None
        self._qty = None
        self.discriminator = None
        if payment_method is not None:
            self.payment_method = payment_method
        if qty is not None:
            self.qty = qty

    @property
    def payment_method(self):
        """Gets the payment_method of this WithdrawalRequestData.  # noqa: E501

        The payment method (cryptocode + network) of the withdrawal.  # noqa: E501

        :return: The payment_method of this WithdrawalRequestData.  # noqa: E501
        :rtype: str
        """
        return self._payment_method

    @payment_method.setter
    def payment_method(self, payment_method):
        """Sets the payment_method of this WithdrawalRequestData.

        The payment method (cryptocode + network) of the withdrawal.  # noqa: E501

        :param payment_method: The payment_method of this WithdrawalRequestData.  # noqa: E501
        :type: str
        """

        self._payment_method = payment_method

    @property
    def qty(self):
        """Gets the qty of this WithdrawalRequestData.  # noqa: E501

        The qty to withdraw.  # noqa: E501

        :return: The qty of this WithdrawalRequestData.  # noqa: E501
        :rtype: float
        """
        return self._qty

    @qty.setter
    def qty(self, qty):
        """Sets the qty of this WithdrawalRequestData.

        The qty to withdraw.  # noqa: E501

        :param qty: The qty of this WithdrawalRequestData.  # noqa: E501
        :type: float
        """

        self._qty = qty

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WithdrawalRequestData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WithdrawalRequestData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
