# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CryptoCodePreviewBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'derivation_scheme': 'str'
    }

    attribute_map = {
        'derivation_scheme': 'derivationScheme'
    }

    def __init__(self, derivation_scheme=None):  # noqa: E501
        """CryptoCodePreviewBody - a model defined in Swagger"""  # noqa: E501
        self._derivation_scheme = None
        self.discriminator = None
        if derivation_scheme is not None:
            self.derivation_scheme = derivation_scheme

    @property
    def derivation_scheme(self):
        """Gets the derivation_scheme of this CryptoCodePreviewBody.  # noqa: E501

        The derivation scheme  # noqa: E501

        :return: The derivation_scheme of this CryptoCodePreviewBody.  # noqa: E501
        :rtype: str
        """
        return self._derivation_scheme

    @derivation_scheme.setter
    def derivation_scheme(self, derivation_scheme):
        """Sets the derivation_scheme of this CryptoCodePreviewBody.

        The derivation scheme  # noqa: E501

        :param derivation_scheme: The derivation_scheme of this CryptoCodePreviewBody.  # noqa: E501
        :type: str
        """

        self._derivation_scheme = derivation_scheme

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CryptoCodePreviewBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CryptoCodePreviewBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
