# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OnChainPaymentMethodData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crypto_code': 'str'
    }

    attribute_map = {
        'crypto_code': 'cryptoCode'
    }

    def __init__(self, crypto_code=None):  # noqa: E501
        """OnChainPaymentMethodData - a model defined in Swagger"""  # noqa: E501
        self._crypto_code = None
        self.discriminator = None
        if crypto_code is not None:
            self.crypto_code = crypto_code

    @property
    def crypto_code(self):
        """Gets the crypto_code of this OnChainPaymentMethodData.  # noqa: E501

        Crypto code of the payment method  # noqa: E501

        :return: The crypto_code of this OnChainPaymentMethodData.  # noqa: E501
        :rtype: str
        """
        return self._crypto_code

    @crypto_code.setter
    def crypto_code(self, crypto_code):
        """Sets the crypto_code of this OnChainPaymentMethodData.

        Crypto code of the payment method  # noqa: E501

        :param crypto_code: The crypto_code of this OnChainPaymentMethodData.  # noqa: E501
        :type: str
        """

        self._crypto_code = crypto_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OnChainPaymentMethodData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OnChainPaymentMethodData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
