# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PatchOnChainTransactionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'labels': 'list[str]'
    }

    attribute_map = {
        'comment': 'comment',
        'labels': 'labels'
    }

    def __init__(self, comment=None, labels=None):  # noqa: E501
        """PatchOnChainTransactionRequest - a model defined in Swagger"""  # noqa: E501
        self._comment = None
        self._labels = None
        self.discriminator = None
        if comment is not None:
            self.comment = comment
        if labels is not None:
            self.labels = labels

    @property
    def comment(self):
        """Gets the comment of this PatchOnChainTransactionRequest.  # noqa: E501

        Transaction comment  # noqa: E501

        :return: The comment of this PatchOnChainTransactionRequest.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this PatchOnChainTransactionRequest.

        Transaction comment  # noqa: E501

        :param comment: The comment of this PatchOnChainTransactionRequest.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def labels(self):
        """Gets the labels of this PatchOnChainTransactionRequest.  # noqa: E501

        Transaction labels  # noqa: E501

        :return: The labels of this PatchOnChainTransactionRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this PatchOnChainTransactionRequest.

        Transaction labels  # noqa: E501

        :param labels: The labels of this PatchOnChainTransactionRequest.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PatchOnChainTransactionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchOnChainTransactionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
