# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PayoutsPayoutIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'revision': 'int',
        'rate_rule': 'str'
    }

    attribute_map = {
        'revision': 'revision',
        'rate_rule': 'rateRule'
    }

    def __init__(self, revision=None, rate_rule=None):  # noqa: E501
        """PayoutsPayoutIdBody - a model defined in Swagger"""  # noqa: E501
        self._revision = None
        self._rate_rule = None
        self.discriminator = None
        if revision is not None:
            self.revision = revision
        if rate_rule is not None:
            self.rate_rule = rate_rule

    @property
    def revision(self):
        """Gets the revision of this PayoutsPayoutIdBody.  # noqa: E501

        The revision number of the payout being modified  # noqa: E501

        :return: The revision of this PayoutsPayoutIdBody.  # noqa: E501
        :rtype: int
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this PayoutsPayoutIdBody.

        The revision number of the payout being modified  # noqa: E501

        :param revision: The revision of this PayoutsPayoutIdBody.  # noqa: E501
        :type: int
        """

        self._revision = revision

    @property
    def rate_rule(self):
        """Gets the rate_rule of this PayoutsPayoutIdBody.  # noqa: E501

        The rate rule to calculate the rate of the payout. This can also be a fixed decimal. (if null or unspecified, will use the same rate setting as the store's settings)  # noqa: E501

        :return: The rate_rule of this PayoutsPayoutIdBody.  # noqa: E501
        :rtype: str
        """
        return self._rate_rule

    @rate_rule.setter
    def rate_rule(self, rate_rule):
        """Sets the rate_rule of this PayoutsPayoutIdBody.

        The rate rule to calculate the rate of the payout. This can also be a fixed decimal. (if null or unspecified, will use the same rate setting as the store's settings)  # noqa: E501

        :param rate_rule: The rate_rule of this PayoutsPayoutIdBody.  # noqa: E501
        :type: str
        """

        self._rate_rule = rate_rule

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PayoutsPayoutIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PayoutsPayoutIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
