# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PaymentRequestsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def payment_requests_archive_payment_request(self, store_id, payment_request_id, **kwargs):  # noqa: E501
        """Archive payment request  # noqa: E501

        Archives the specified payment request.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_archive_payment_request(store_id, payment_request_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str store_id: The store the payment request belongs to (required)
        :param str payment_request_id: The payment request to remove (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.payment_requests_archive_payment_request_with_http_info(store_id, payment_request_id, **kwargs)  # noqa: E501
        else:
            (data) = self.payment_requests_archive_payment_request_with_http_info(store_id, payment_request_id, **kwargs)  # noqa: E501
            return data

    def payment_requests_archive_payment_request_with_http_info(self, store_id, payment_request_id, **kwargs):  # noqa: E501
        """Archive payment request  # noqa: E501

        Archives the specified payment request.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_archive_payment_request_with_http_info(store_id, payment_request_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str store_id: The store the payment request belongs to (required)
        :param str payment_request_id: The payment request to remove (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['store_id', 'payment_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method payment_requests_archive_payment_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'store_id' is set
        if ('store_id' not in params or
                params['store_id'] is None):
            raise ValueError("Missing the required parameter `store_id` when calling `payment_requests_archive_payment_request`")  # noqa: E501
        # verify the required parameter 'payment_request_id' is set
        if ('payment_request_id' not in params or
                params['payment_request_id'] is None):
            raise ValueError("Missing the required parameter `payment_request_id` when calling `payment_requests_archive_payment_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'store_id' in params:
            path_params['storeId'] = params['store_id']  # noqa: E501
        if 'payment_request_id' in params:
            path_params['paymentRequestId'] = params['payment_request_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API_Key', 'Basic']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/stores/{storeId}/payment-requests/{paymentRequestId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def payment_requests_create_payment_request(self, body, store_id, **kwargs):  # noqa: E501
        """Create a new payment request  # noqa: E501

        Create a new payment request  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_create_payment_request(body, store_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PaymentRequestBaseData body: (required)
        :param str store_id: The store to query (required)
        :return: PaymentRequestData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.payment_requests_create_payment_request_with_http_info(body, store_id, **kwargs)  # noqa: E501
        else:
            (data) = self.payment_requests_create_payment_request_with_http_info(body, store_id, **kwargs)  # noqa: E501
            return data

    def payment_requests_create_payment_request_with_http_info(self, body, store_id, **kwargs):  # noqa: E501
        """Create a new payment request  # noqa: E501

        Create a new payment request  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_create_payment_request_with_http_info(body, store_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PaymentRequestBaseData body: (required)
        :param str store_id: The store to query (required)
        :return: PaymentRequestData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'store_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method payment_requests_create_payment_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `payment_requests_create_payment_request`")  # noqa: E501
        # verify the required parameter 'store_id' is set
        if ('store_id' not in params or
                params['store_id'] is None):
            raise ValueError("Missing the required parameter `store_id` when calling `payment_requests_create_payment_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'store_id' in params:
            path_params['storeId'] = params['store_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API_Key', 'Basic']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/stores/{storeId}/payment-requests', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaymentRequestData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def payment_requests_get_payment_request(self, store_id, payment_request_id, **kwargs):  # noqa: E501
        """Get payment request  # noqa: E501

        View information about the specified payment request  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_get_payment_request(store_id, payment_request_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str store_id: The store to fetch (required)
        :param str payment_request_id: The payment request to fetch (required)
        :return: PaymentRequestData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.payment_requests_get_payment_request_with_http_info(store_id, payment_request_id, **kwargs)  # noqa: E501
        else:
            (data) = self.payment_requests_get_payment_request_with_http_info(store_id, payment_request_id, **kwargs)  # noqa: E501
            return data

    def payment_requests_get_payment_request_with_http_info(self, store_id, payment_request_id, **kwargs):  # noqa: E501
        """Get payment request  # noqa: E501

        View information about the specified payment request  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_get_payment_request_with_http_info(store_id, payment_request_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str store_id: The store to fetch (required)
        :param str payment_request_id: The payment request to fetch (required)
        :return: PaymentRequestData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['store_id', 'payment_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method payment_requests_get_payment_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'store_id' is set
        if ('store_id' not in params or
                params['store_id'] is None):
            raise ValueError("Missing the required parameter `store_id` when calling `payment_requests_get_payment_request`")  # noqa: E501
        # verify the required parameter 'payment_request_id' is set
        if ('payment_request_id' not in params or
                params['payment_request_id'] is None):
            raise ValueError("Missing the required parameter `payment_request_id` when calling `payment_requests_get_payment_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'store_id' in params:
            path_params['storeId'] = params['store_id']  # noqa: E501
        if 'payment_request_id' in params:
            path_params['paymentRequestId'] = params['payment_request_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API_Key', 'Basic']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/stores/{storeId}/payment-requests/{paymentRequestId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaymentRequestData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def payment_requests_get_payment_requests(self, store_id, **kwargs):  # noqa: E501
        """Get payment requests  # noqa: E501

        View information about the existing payment requests  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_get_payment_requests(store_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str store_id: The store to query (required)
        :return: PaymentRequestDataList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.payment_requests_get_payment_requests_with_http_info(store_id, **kwargs)  # noqa: E501
        else:
            (data) = self.payment_requests_get_payment_requests_with_http_info(store_id, **kwargs)  # noqa: E501
            return data

    def payment_requests_get_payment_requests_with_http_info(self, store_id, **kwargs):  # noqa: E501
        """Get payment requests  # noqa: E501

        View information about the existing payment requests  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_get_payment_requests_with_http_info(store_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str store_id: The store to query (required)
        :return: PaymentRequestDataList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['store_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method payment_requests_get_payment_requests" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'store_id' is set
        if ('store_id' not in params or
                params['store_id'] is None):
            raise ValueError("Missing the required parameter `store_id` when calling `payment_requests_get_payment_requests`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'store_id' in params:
            path_params['storeId'] = params['store_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API_Key', 'Basic']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/stores/{storeId}/payment-requests', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaymentRequestDataList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def payment_requests_update_payment_request(self, body, store_id, payment_request_id, **kwargs):  # noqa: E501
        """Update payment request  # noqa: E501

        Update a payment request  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_update_payment_request(body, store_id, payment_request_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PaymentRequestBaseData body: (required)
        :param str store_id: The store to query (required)
        :param str payment_request_id: The payment request to update (required)
        :return: PaymentRequestData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.payment_requests_update_payment_request_with_http_info(body, store_id, payment_request_id, **kwargs)  # noqa: E501
        else:
            (data) = self.payment_requests_update_payment_request_with_http_info(body, store_id, payment_request_id, **kwargs)  # noqa: E501
            return data

    def payment_requests_update_payment_request_with_http_info(self, body, store_id, payment_request_id, **kwargs):  # noqa: E501
        """Update payment request  # noqa: E501

        Update a payment request  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_requests_update_payment_request_with_http_info(body, store_id, payment_request_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PaymentRequestBaseData body: (required)
        :param str store_id: The store to query (required)
        :param str payment_request_id: The payment request to update (required)
        :return: PaymentRequestData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'store_id', 'payment_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method payment_requests_update_payment_request" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `payment_requests_update_payment_request`")  # noqa: E501
        # verify the required parameter 'store_id' is set
        if ('store_id' not in params or
                params['store_id'] is None):
            raise ValueError("Missing the required parameter `store_id` when calling `payment_requests_update_payment_request`")  # noqa: E501
        # verify the required parameter 'payment_request_id' is set
        if ('payment_request_id' not in params or
                params['payment_request_id'] is None):
            raise ValueError("Missing the required parameter `payment_request_id` when calling `payment_requests_update_payment_request`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'store_id' in params:
            path_params['storeId'] = params['store_id']  # noqa: E501
        if 'payment_request_id' in params:
            path_params['paymentRequestId'] = params['payment_request_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['API_Key', 'Basic']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/stores/{storeId}/payment-requests/{paymentRequestId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaymentRequestData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
